select * from customer;
--Q1 what is the total revenue generated by male vs . female customers?
select gender, sum(purchased_amount) as revenue
from customer
group by gender;

--Q2 which customers used a discount but still spend more than the average purchase_amount?
select customer_id,purchased_amount
from customer 
where discount_applied='Yes' and purchased_amount >= (select avg(purchased_amount) from customer);

--Q3 Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) as average_rating
from customer 
group by item_purchased
order by average_rating desc limit 5;

--Q4 compare the average purchase amounts between standard and express shippig 
select shipping_type,ROUND(AVG(purchased_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5 Do Subscribed customers spend more? Compare average spend and total revenue
select subscription_status,count(customer_id) as total_customer, 
round(avg(purchased_amount),2) as average_sale,
sum(purchased_amount) as total_revenue
from customer
group by subscription_status;

--Q6 which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,count(item_purchased) as total_item
from customer
where discount_applied='Yes'
group by item_purchased
order by total_item desc limit 5;


select item_purchased,
round(100 * sum(case when discount_applied= 'Yes' then 1 else 0 end) /count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7 Segment customers into New , Returning , and Loyal based on their total
--numer of the previous purchase , and show the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment


--Q8 what are the top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;


--Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

--Q10 What is the revenue contribution of each age group?
select age_group,
sum(purchased_amount) as total_revenue
from customer
group by age_group
order by total_revenue  desc;